### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by andrewlangston** [michaelhcho91/finstagram#2]
Michael,

Great job on your sample state! Two brief notes:

- [x] I'm not sure we need to keep track of users' `postIds` and `likedPostIds` in our frontend state. These relationships will be capture by foreign keys within the `posts` slice of state.
- [x] Within our `posts` slice of state, `likerIds` should *always* be an array, even if it contains only one id. This will ensure we can always rely on array methods like `map` and `filter` without running into errors and/or having to type-check every time we want to iterate over that part of our state.

Let me know if you have any questions!

**Comment by andrewlangston** [comment]
I think it makes sense to keep track of `name` for all users, which we can do in the `users` slice of state. Please do add this to your sample state.

I am not sure what you mean by "sorting data". Would you mind clarifying? Thanks!

**Comment by michaelhcho91** [comment]
`name` included for all users.

In the `ui` slice of state, I have a key of `postFeed` that I am not sure what to do with. According to the curriculum's state shape page:

https://github.com/appacademy/curriculum/blob/master/full-stack-project/homeworks/proposal-prep/state-shape.md

"ui - contains view configuration data, such as: **sorting**, pagination, loading screens, et."

**Comment by andrewlangston** [comment]
Michael - this is interesting - let's discuss when we meet today. There are a few ways to handle post filtering to reflect different feeds.
