### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by andrewlangston** [michaelhcho91/finstagram#3]
Michael - great work here! One comment on your frontend routes:

- [x] I don't believe we need `/posts/new` and `/posts/:postId/edit`, as Instagram doesn't feature a brand new view when uploading and editing photos. This can be removed.

Let me know if you have questions!

**Comment by michaelhcho91** [comment]
`/posts/new` and `/posts/:postId/edit` removed. Thank you!
